[package]
name = "pokurr"
version = "0.1.0"
authors = ["soederpop <jon@dais.com>"]
edition = "2018"

[lib]
name = "libpokurr"
path = "src/lib.rs"

[[bin]]
name = "pokurr"
path = "src/bin.rs"

[dependencies]
rand = "0.3.12"